# ========== DATABASE ==========
#spring.application.name=roarmot
# configuración de la conexión a la base de datos MySQL (Xampp)
#spring.datasource.url=jdbc:mysql://localhost:3306/mymoto?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA/HIBERNATE ==========
# CONFIGURACIÓN DE JPA (HIBERNATE)
# Esto le dice a JPA cómo manejar el esquema de la base de datos.
# - update: Actualiza la tabla si la Entidad ha cambiado (bueno para desarrollo).
# - validate: Verifica la consistencia.
# - create: Crea la tabla desde cero (peligroso en producción).
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true


# ========== FILE UPLOADS ==========
# --- Configuración del Servicio de Almacenamiento de Archivos (FileStorageService) ---
# La ruta de guardado será relativa a la carpeta donde se ejecuta la aplicación.
# Esto asegura que los archivos se guarden fuera del .jar/.war para persistencia.
#file.upload-dir=data/uploads

# Tamaños máximos (IMPORTANTE para fotos de motos)
#spring.servlet.multipart.max-file-size=10MB      
#spring.servlet.multipart.max-request-size=15MB   

# ========== EMAIL ==========
# Email Configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=roarmot000@gmail.com
#spring.mail.password=rflrcmzrgdlnwrcb
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# ========== THYMELEAF ==========
# Template Configuration
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html

# ========== Servicio Web Google Maps Platform API Places ==========
#google.maps.api.key=AIzaSyCnd5XbgIUmbTT0ZXeTxx5RjElXaWJJj5c
#google.maps.api.url=https://maps.googleapis.com/maps/api/place/nearbysearch/json
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${PORT:8080}

file.upload-dir=uploads